Repository OpenFAST/openfast, pull requests merged in 2019-03, with the labels that each got.

#255 Fixes #254 - Updates the testing documentation for Windows with instructions to copy r-test folder
  docs/source/testing/regression_test_windows.rst
Labels: Type: Documentation

#258 Allowing number of Morison number to be 0 (see #79)
  modules-local/hydrodyn/src/HydroDyn.f90
  modules-local/openfast-library/src/FAST_Solver.f90
Labels: Module: HydroDyn

#259 Add API changelog to the docs
  docs/source/install/install_cmake_cygwin.rst
  docs/source/user/api_change.rst
  docs/source/user/index.rst
Labels: Type: Documentation, Type: Enhancement

#257 Zero padding of VTK names, and log10 of zero (see #250)
  modules-local/openfast-library/src/FAST_Subs.f90
Labels: Type: Bug

#262 A few updates to the documentation
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  docs/source/dev/build_doc.rst
  docs/source/dev/debugging.rst
  docs/source/dev/dev_phil.rst
  docs/source/dev/github_workflow.rst
  docs/source/dev/index.rst
  docs/source/install/install_cmake_cygwin.rst
  docs/source/testing/index.rst
  docs/source/this_doc.rst
  docs/source/user/beamdyn/input_files.rst
  docs/source/user/index.rst
Labels: Type: Documentation

#263 Sync the git versions for windows and linux builds
  vs-build/CreateGitVersion.bat
Labels: Type: Bug

#239 Adding safety on number of lines and number of fields per line when WaveMode=6 (Should Fix #118)
  modules-local/hydrodyn/src/HydroDyn_DriverCode.f90
  modules-local/hydrodyn/src/UserWaves.f90
  modules-local/nwtc-library/src/NWTC_IO.f90
Labels: Module: HydroDyn, Type: Enhancement
