Repository OpenFAST/openfast, pull requests merged in 2020-10, with the labels that each got.

#558 Docs: Refer to conda for installation
  docs/conf.py
  docs/source/install/index.rst
Labels: Type: Documentation

#564 Docs: update OpenFAST solve documentation to include BeamDyn
  docs/OtherSupporting/OpenFAST_Algorithms/OpenFAST_Algorithms.pdf
  docs/OtherSupporting/OpenFAST_Algorithms/OpenFAST_Algorithms.tex
Labels: Type: Documentation

#559 Docs: Update unit test guidance
  docs/source/testing/unit_test.rst
  unit_tests/test_SUBROUTINE.F90
Labels: Type: Documentation, Type: Testing

#577 Updated examples for OpenFAST-Simulink Interface
  glue-codes/simulink/examples/Run_OpenLoop.m
  glue-codes/simulink/examples/Run_Test01_SIG.m
  glue-codes/simulink/src/create_FAST_SFunc.m
  vs-build/FASTlib/FASTlib.vfproj
Labels: Sytem: MATLAB

#579 GitHub Actions Rework
  .github/actions/cmake-config/action.yml
  .github/actions/compile-and-test/Dockerfile
  .github/actions/compile-and-test/action.yml
  .github/actions/compile-and-test/entrypoint.sh
  .github/actions/compile/action.yml
  .github/actions/git-update/action.yml
  .github/actions/tests-gluecode-openfast/action.yml
  .github/actions/tests-module-aerodyn/action.yml
  .github/actions/tests-module-beamdyn/action.yml
  .github/actions/tests-module-hydrodyn/action.yml
  .github/actions/tests-module-nwtclibrary/action.yml
  .github/workflows/automated-dev-tests.yml
  .github/workflows/continuous-integration-workflow.yml
  reg_tests/CMakeLists.txt
  share/docker/openfast_dev/Dockerfile
  share/docker/openfast_ubuntu/Dockerfile
  unit_tests/CMakeLists.txt
Labels: Type: Enhancement, Type: Testing
